$(function(){
	$(".howtoplay").click(function(){
		$(".howtoplaybox").fadeIn();
		$(".windowbox").fadeOut();
	});
	$(".backbox").click(function(){
		$(".howtoplaybox").fadeOut();
		$(".windowbox").fadeIn();
	});
});